#!/bin/bash

#rm -rf TMP
#git clone -q git@github.com:jekyll-toolbox/TEMPLATE.github.io.git TMP
for _F in TMP/run* TMP/Makefile
do
	_F=${_F#*/}
	echo "### ${_F}-----------------------------------------------------"
	diff $_F TMP/$_F
done
